apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kubekloud-api

resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - serviceaccount.yaml
  - postgres-pvc.yaml
  - postgres-deployment.yaml
  - postgres-service.yaml
  - api-deployment.yaml
  - api-service.yaml

